# -*- coding: utf-8 -*-
"""Cancerproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1juWiix7w5KXtxdmsaRvXCZyJciwgax2z
"""

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
cancer = load_breast_cancer()
print("Cancer.keys():\n{}".format(cancer.keys()))

print("Shape of cancer data: {}".format(cancer.data.shape))
import numpy as np

print("Sample counts per class:")
for name, count in zip(cancer.target_names, np.bincount(cancer.target)):
    print(f"{name}: {count}")

print("Feature names:\n{}".format(cancer.feature_names))

from matplotlib import pyplot as plt
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, random_state=66)
print(X_train.shape)
print(X_test.shape)
training_accuracy = []
test_accuracy = []
for neighbour in range(1, 11):
    knn = KNeighborsClassifier(n_neighbors=neighbour)
    knn.fit(X_train, y_train)
    training_accuracy.append(knn.score(X_train, y_train))
    test_accuracy.append(knn.score(X_test, y_test))
print(training_accuracy)
print(test_accuracy)
plt.plot(range(1, 11), training_accuracy, label="training accuracy")
plt.plot(range(1, 11), test_accuracy, label="test accuracy")
plt.ylabel("Accuracy")
plt.xlabel("n_neighbors")
plt.legend()
plt.show()

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
import pandas as pd
import matplotlib.pyplot as plt
data = load_breast_cancer()
df=pd.DataFrame(data.data,columns=data.feature_names)
df.sample(5)

df.info()

df.describe()

df2=pd.DataFrame(data.target,columns=['target'])
df2.sample(5)

class_counts=df2["target"].value_counts()
plt.pie(class_counts, labels=class_counts.index, autopct='%1.2f%%', colors=['red', 'green'])

X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.33, random_state=42)

model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(y_pred[:15])

accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")